name: iProtector
author: LDX
version: 3.1.2
main: LDX\iProtector\Main
load: POSTWORLD
api: [5.0.0]
website: https://github.com/LDX-MCPE/iProtector

commands:
  area:
    description: Manage protected areas
    usage: "/area <pos1|pos2|create|list|here|flag|whitelist|delete|tp>"
    permission: iprotector.command.area

permissions:

  iprotector:
    description: Access to all iProtector features
    default: false
    children:
      iprotector.command: true
      iprotector.access: true

  iprotector.command:
    description: Access to all iProtector commands
    default: false
    children:
      iprotector.command.area: true

  iprotector.access:
    description: Allows editing terrain in protected areas
    default: op

  iprotector.command.area:
    description: Allows use of /area command
    default: op
    children:
      iprotector.command.area.pos1: true
      iprotector.command.area.pos2: true
      iprotector.command.area.create: true
      iprotector.command.area.list: true
      iprotector.command.area.here: true
      iprotector.command.area.flag: true
      iprotector.command.area.delete: true
      iprotector.command.area.whitelist: true
      iprotector.command.area.tp: true

  iprotector.command.area.pos1:
    description: Set position 1
    default: op

  iprotector.command.area.pos2:
    description: Set position 2
    default: op

  iprotector.command.area.create:
    description: Create areas
    default: op

  iprotector.command.area.list:
    description: List areas
    default: op

  iprotector.command.area.here:
    description: Show area you are in
    default: op

  iprotector.command.area.flag:
    description: Modify area flags
    default: op

  iprotector.command.area.delete:
    description: Delete areas
    default: op

  iprotector.command.area.whitelist:
    description: Manage area whitelist
    default: op

  iprotector.command.area.tp:
    description: Teleport to area
    default: op
