name: iProtector
author: LDX
version: 3.1.2
main: LDX\iProtector\Main
load: POSTWORLD
api: [5.0.0]

commands:
  area:
    description: Manage protected areas
    usage: "/area <pos1|pos2|create|list|delete>"
    permission: iprotector.command.area

permissions:
  iprotector.command.area:
    default: op
  iprotector.access:
    default: op
